<?php

use Illuminate\Database\Seeder;

// use Illuminate\Database\Eloquent\Model;

// use Illuminate\Support\Facades\Auth;
use Carbon\Carbon as Carbon;
// use App\Models\ProvincesModel as Province;

class ProvinceSeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	DB::table('provinces')->delete();
    	// Province::truncate();
        DB::table('provinces')->insert([
            [
            'name' => 'ACEH',
            'description' => '-',
            'logo' => '',
            // 'created_by' => 1,
            'created_at' => Carbon::now(),
            // 'updated_by' => 1,
            'updated_at' => Carbon::now(),
            ],
            [
            'name' => 'SUMATERA UTARA',
            'description' => '-',
            'logo' => '',
            // 'created_by' => 1,
            'created_at' => Carbon::now(),
            // 'updated_by' => 1,
            'updated_at' => Carbon::now(),
            ],
            [
            'name' => 'SUMATERA BARAT',
            'description' => '-',
            'logo' => '',
            // 'created_by' => 1,
            'created_at' => Carbon::now(),
            // 'updated_by' => 1,
            'updated_at' => Carbon::now(),
            ],
            [
            'name' => 'RIAU',
            'description' => '-',
            'logo' => '',
            // 'created_by' => 1,
            'created_at' => Carbon::now(),
            // 'updated_by' => 1,
            'updated_at' => Carbon::now(),
            ],
            [
            'name' => 'JAMBI',
            'description' => '-',
            'logo' => '',
            // 'created_by' => 1,
            'created_at' => Carbon::now(),
            // 'updated_by' => 1,
            'updated_at' => Carbon::now(),
            ],
            [
            'name' => 'SUMATERA SELATAN',
            'description' => '-',
            'logo' => '',
            // 'created_by' => 1,
            'created_at' => Carbon::now(),
            // 'updated_by' => 1,
            'updated_at' => Carbon::now(),
            ],
            [
            'name' => 'BENGKULU',
            'description' => '-',
            'logo' => '',
            // 'created_by' => 1,
            'created_at' => Carbon::now(),
            // 'updated_by' => 1,
            'updated_at' => Carbon::now(),
            ],
            [
            'name' => 'LAMPUNG',
            'description' => '-',
            'logo' => '',
            // 'created_by' => 1,
            'created_at' => Carbon::now(),
            // 'updated_by' => 1,
            'updated_at' => Carbon::now(),
            ],
            [
            'name' => 'KEPULAUAN BANGKA BELITUNG',
            'description' => '-',
            'logo' => '',
            // 'created_by' => 1,
            'created_at' => Carbon::now(),
            // 'updated_by' => 1,
            'updated_at' => Carbon::now(),
            ],
            [
            'name' => 'KEPULAUAN RIAU',
            'description' => '-',
            'logo' => '',
            // 'created_by' => 1,
            'created_at' => Carbon::now(),
            // 'updated_by' => 1,
            'updated_at' => Carbon::now(),
            ],
            [
            'name' => 'DKI JAKARTA',
            'description' => '-',
            'logo' => '',
            // 'created_by' => 1,
            'created_at' => Carbon::now(),
            // 'updated_by' => 1,
            'updated_at' => Carbon::now(),
            ],
            [
            'name' => 'JAWA BARAT',
            'description' => '-',
            'logo' => '',
            // 'created_by' => 1,
            'created_at' => Carbon::now(),
            // 'updated_by' => 1,
            'updated_at' => Carbon::now(),
            ],
            [
            'name' => 'JAWA TENGAH',
            'description' => '-',
            'logo' => '',
            // 'created_by' => 1,
            'created_at' => Carbon::now(),
            // 'updated_by' => 1,
            'updated_at' => Carbon::now(),
            ],
            [
            'name' => 'DAERAH ISTIMEWA YOGYAKARTA',
            'description' => '-',
            'logo' => '',
            // 'created_by' => 1,
            'created_at' => Carbon::now(),
            // 'updated_by' => 1,
            'updated_at' => Carbon::now(),
            ],
            [
            'name' => 'JAWA TIMUR',
            'description' => '-',
            'logo' => '',
            // 'created_by' => 1,
            'created_at' => Carbon::now(),
            // 'updated_by' => 1,
            'updated_at' => Carbon::now(),
            ],
            [
            'name' => 'BANTEN',
            'description' => '-',
            'logo' => '',
            // 'created_by' => 1,
            'created_at' => Carbon::now(),
            // 'updated_by' => 1,
            'updated_at' => Carbon::now(),
            ],
            [
            'name' => 'BALI',
            'description' => '-',
            'logo' => '',
            // 'created_by' => 1,
            'created_at' => Carbon::now(),
            // 'updated_by' => 1,
            'updated_at' => Carbon::now(),
            ],
            [
            'name' => 'NUSA TENGGARA BARAT',
            'description' => '-',
            'logo' => '',
            // 'created_by' => 1,
            'created_at' => Carbon::now(),
            // 'updated_by' => 1,
            'updated_at' => Carbon::now(),
            ],
            [
            'name' => 'NUSA TENGGARA TIMUR',
            'description' => '-',
            'logo' => '',
            // 'created_by' => 1,
            'created_at' => Carbon::now(),
            // 'updated_by' => 1,
            'updated_at' => Carbon::now(),
            ],
            [
            'name' => 'KALIMANTAN BARAT',
            'description' => '-',
            'logo' => '',
            // 'created_by' => 1,
            'created_at' => Carbon::now(),
            // 'updated_by' => 1,
            'updated_at' => Carbon::now(),
            ],
            [
            'name' => 'KALIMANTAN TENGAH',
            'description' => '-',
            'logo' => '',
            // 'created_by' => 1,
            'created_at' => Carbon::now(),
            // 'updated_by' => 1,
            'updated_at' => Carbon::now(),
            ],
            [
            'name' => 'KALIMANTAN SELATAN',
            'description' => '-',
            'logo' => '',
            // 'created_by' => 1,
            'created_at' => Carbon::now(),
            // 'updated_by' => 1,
            'updated_at' => Carbon::now(),
            ],
            [
            'name' => 'KALIMANTAN TIMUR',
            'description' => '-',
            'logo' => '',
            // 'created_by' => 1,
            'created_at' => Carbon::now(),
            // 'updated_by' => 1,
            'updated_at' => Carbon::now(),
            ],
            [
            'name' => 'SULAWESI UTARA',
            'description' => '-',
            'logo' => '',
            // 'created_by' => 1,
            'created_at' => Carbon::now(),
            // 'updated_by' => 1,
            'updated_at' => Carbon::now(),
            ],
            [
            'name' => 'SULAWESI TENGAH',
            'description' => '-',
            'logo' => '',
            // 'created_by' => 1,
            'created_at' => Carbon::now(),
            // 'updated_by' => 1,
            'updated_at' => Carbon::now(),
            ],
            [
            'name' => 'SULAWESI SELATAN',
            'description' => '-',
            'logo' => '',
            // 'created_by' => 1,
            'created_at' => Carbon::now(),
            // 'updated_by' => 1,
            'updated_at' => Carbon::now(),
            ],
            [
            'name' => 'SULAWESI TENGGARA',
            'description' => '-',
            'logo' => '',
            // 'created_by' => 1,
            'created_at' => Carbon::now(),
            // 'updated_by' => 1,
            'updated_at' => Carbon::now(),
            ],
            [
            'name' => 'GORONTALO',
            'description' => '-',
            'logo' => '',
            // 'created_by' => 1,
            'created_at' => Carbon::now(),
            // 'updated_by' => 1,
            'updated_at' => Carbon::now(),
            ],
            [
            'name' => 'SULAWESI BARAT',
            'description' => '-',
            'logo' => '',
            // 'created_by' => 1,
            'created_at' => Carbon::now(),
            // 'updated_by' => 1,
            'updated_at' => Carbon::now(),
            ],
            [
            'name' => 'MALUKU',
            'description' => '-',
            'logo' => '',
            // 'created_by' => 1,
            'created_at' => Carbon::now(),
            // 'updated_by' => 1,
            'updated_at' => Carbon::now(),
            ],
            [
            'name' => 'MALUKU UTARA',
            'description' => '-',
            'logo' => '',
            // 'created_by' => 1,
            'created_at' => Carbon::now(),
            // 'updated_by' => 1,
            'updated_at' => Carbon::now(),
            ],
            [
            'name' => 'PAPUA',
            'description' => '-',
            'logo' => '',
            // 'created_by' => 1,
            'created_at' => Carbon::now(),
            // 'updated_by' => 1,
            'updated_at' => Carbon::now(),
            ],
            [
            'name' => 'PAPUA BARAT',
            'description' => '-',
            'logo' => '',
            // 'created_by' => 1,
            'created_at' => Carbon::now(),
            // 'updated_by' => 1,
            'updated_at' => Carbon::now(),
            ]
        ]);
    }
}
